# Generated by Django 3.1.5 on 2021-02-02 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe', to=settings.AUTH_USER_MODEL)),
                ('user_favorit', models.ManyToManyField(blank=True, related_name='favorit_recipe', to=settings.AUTH_USER_MODEL)),
                ('user_recommend', models.ManyToManyField(blank=True, related_name='recommend_recipe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
